USE smartGolf

CREATE TABLE Jugardor (
Id INT  UNSIGNED AUTO_INCREMENT PRIMARY KEY,
Nombre VARCHAR(30) NOT NULL,
Apellidos VARCHAR(30) NOT NULL,
Clave VARCHAR(10) NOT NULL,
EsAdmin BOOL NOT NULL
)

CREATE TABLE Campeonato (
Id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
Nombre VARCHAR(30) NOT NULL
)

CREATE TABLE Cancha (
Id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
Nombre VARCHAR(30)
)

CREATE TABLE hoyo (
Id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
IdCancha INT UNSIGNED,
Par INT,
Numero INT,
FOREIGN KEY (IdCancha) REFERENCES Cancha(Id)
)

CREATE TABLE Feacha (
Id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
IdCampeonato INT UNSIGNED,
Numero INT,
IdPrimeraCancha INT UNSIGNED,
IdSegundaCancha INT UNSIGNED,
FOREIGN KEY (IdCampeonato) REFERENCES Campeonato(Id),
FOREIGN KEY (IdPrimeraCancha) REFERENCES Cancha(Id),
FOREIGN KEY (IdSegundaCancha) REFERENCES Cancha(Id)
)

CREATE TABLE juego (
Id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
IdJugador INT UNSIGNED,
IdControlador INT UNSIGNED,
IdFecha INT UNSIGNED,
FOREIGN KEY (IdJugador) REFERENCES Jugardor(Id),
FOREIGN KEY (IdControlador) REFERENCES Jugardor(Id),
FOREIGN KEY (IdFecha) REFERENCES Feacha(Id)
)

CREATE TABLE Puntuacion (
	IdJuego INT UNSIGNED,
	IdHoyo INT UNSIGNED,
	Golpes INT,
	PRIMARY KEY (IdJuego, IdHoyo),
	FOREIGN KEY (IdHoyo) REFERENCES hoyo(Id),
	FOREIGN KEY (IdJuego) REFERENCES juego(Id)
)