USE smartGolf

CREATE TABLE Jugardor (
Id INT  UNSIGNED AUTO_INCREMENT PRIMARY KEY,
Nombre VARCHAR(30) NOT NULL,
Apellidos VARCHAR(30) NOT NULL,
Clave VARCHAR(10) NOT NULL
)

CREATE TABLE Campeonato (
Id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
Nombre VARCHAR(30) NOT NULL
)

CREATE TABLE Cancha (
Id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
Nombre VARCHAR(30)
)

CREATE TABLE hoyo (
Id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
IdCancha INT,
Par INT,
Numero INT,
FOREING KEY (IdCancha) REFERENCES Cancha(Id)
)

CREATE TABLE Feacha (
Id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
IdCampeonato INT,
Numero INT,
IdPrimeraCancha INT,
IdSegundaCancha INT,
FOREING KEY (IdCampeonato) REFERENCES Campeonato(Id),
FOREING KEY (IdPrimeraCancha) REFERENCES Cancha(Id),
FOREING KEY (IdSegundaCancha) REFERENCES Cancha(Id)
)

CREATE TABLE juego (
Id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
IdJugador INT,
IdControlador INT,
IdFecha INT,
FOREING KEY (IdJugador) REFERENCES Jugardor(Id),
FOREING KEY (IdControlador) REFERENCES Jugardor(Id),
FOREING KEY (IdFecha) REFERENCES Feacha(Id)
)

CREATE TABLE Puntuacion (
	IdJuego INT PRIMARY KEY,
	IdHoyo INT PRIMARY KEY,
	Golpes INT,
	FOREING KEY (IdHoyo) REFERENCES hoyo(Id),
	FOREING KEY (IdJuego) REFERENCES juego(Id)
)